# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  setup_travis
  desc "Execute tests"
  lane :tests do
    build_n_test()    
  end
end

def build_n_test
  scan(scheme: "Camp", configuration: "Debug")
  gym(
    scheme: "Camp",
    export_xcargs: "-allowProvisioningUpdates"
  )
  slack_success_msg
end

def slack_success_msg
  slack(
    message: "✅ Your app passed in all tests!",
    success: true,
    slack_url: "https://hooks.slack.com/services/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",     
    default_payloads: [:git_branch, :git_author, :last_git_commit_message]
  )
end

lane :dev do
  cert(
    development: true,
    output_path: "keys/iOS/Development/"
  )

  register_devices(
    devices: {
      "iPhone Bruno" => "6cd8df5fd83f641340e1e07a536d6ed1725d54f1"
    }
  )

  sigh(
    development: true,
    output_path: "keys/iOS/Development",
    cert_id: "GLFLKQVLJ9",
    provisioning_name: "Camp Profile",
    filename: "DevelopmentProvisioningProfile.mobileprovision"    
  )
end

#def slack_error_msg(exception)
#  slack(
#    message: "❌ Lane failed with exception: #{exception}",
#    success: false,
#    slack_url: "https://hooks.slack.com/services/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",          
#  )
#end