# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Execute tests"
  lane :tests do
    run_tests(
        project: "Camp.xcodeproj",
        devices: ["iPhone 8"],
        slack_url: "https://hooks.slack.com/services/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",
        slack_channel: "ci-tests",
        scheme: "CampTests"
    )
  end
end
